[package]
name = "apixels"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.6"
clap = { version = "4.2.1", features = ["derive"] }
anyhow = "1.0.68"
owo-colors = "3.5.0"
rayon = "1.7.0"